### ISSUE TITLE
Trizbort specific commands - prefix

### ISSUE THREAD

**Issue by matthiaswatkins** [JasonLautzenheiser/trizbort#10]
Trizbort currently parses for 'see' and 'region'. I don't know of any situations where this might cause issues due to these verbs being used in-game, but perhaps a standard trizbort prefix for trizbort commands in a script file might make sense to preclude any possible ambiguity: 'trizbort see dragon', etc.

**Comment by JasonLautzenheiser** [comment]
Again I can see this as being useful.

**Comment by matthiaswatkins** [comment]
This ability now exists with pull request #17. I think it can be closed.
