### ISSUE TITLE
Map stats: export error log

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#100]
It would be nice if we could have (file prefix).log to see which rooms are orphans, etc. Tools: E&xport Map Error Logs

This would cover orphaned rooms, potential loops, etc.

And it would be a nice touch if we could have an option to launch the file in a text editor. But it is a bit fiddly.

**Comment by andrewschultz** [comment]
The big barrier I see to implementing this cleanly is that there may be duplicate code as-is.

In MapStatistics.cs we have

    public static int NumberOfLoopingConnections
    {
      get
      {
        return Project.Current.Elements.OfType<Connection>().Count(p =>
        {
          var sourceRoom = p.GetSourceRoom();
          var targetRoom = p.GetTargetRoom();
          return ((sourceRoom != null && targetRoom != null) && (sourceRoom == targetRoom));
        });
      }
    }

I would like to move this to Room.cs so

public int LoopingConnectionsInRoom (room r)
{
  return p.Count( p => { var ... etc.)
}

Then MapStatistics.cs could have

public int LoopingConnectionsInMap
{
  return (sum of all LoopingConnectionsInRoom)
}

Then the hypothetical MapStatLog.cs could have

public int LoopingConnectionsInMap
{
  repeat through rooms;
  if (room.LoopingConnectionsInRoom > 0) { print (room + " has looping connections.");
}

Apologies for the bad pseudocode. But I think in the big picture it'd mean writing the tough code only once.

I don't think this should stop us from writing new statistics to derive. These can be moved over to Rooms.cs or Connectors.cs quickly enough. But I think it'd be useful to have a plan of attack for map export logs before we start to code--maybe you've considered this already but I wanted to write it down and make sure.

**Comment by JasonLautzenheiser** [comment]
I'd like to do some of this for the next version....but would like to come up with a plan first.  I've not completely thought through this with @andrewschultz comments above.

**Comment by andrewschultz** [comment]
My current fix lets the user export basic stats, but it isn't very good about the file names. However, it does reuse the code path for regular stats. I think it's decent code, but it doesn't feel ready for prime time yet. It needs another tweak or two.. But I think it's on the right track so we can close a feature for 1594.
