### ISSUE TITLE
1.5.9.1 lines defined as black by default in 1587 come out as blue

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#104]
Many files in the sample suite show this. Well, pretty much any.

For a simple reproduction case, open 1587, then

R, ctrl-right, R, save.
Tools:map settings:colors and fonts, and set line, border and line text to black.

Then open the file in 1.5.9.1 and the lines are blue.

**Comment by PlNG** [comment]
Similar issue: using the right click line properties tool also changes the color of the line, even setting plain on an otherwise newly created and empty line.

**Comment by JasonLautzenheiser** [comment]
I'm pretty sure this is fixed in the next build.  I made a few changes and have not seen the problem come back up.

**Comment by andrewschultz** [comment]
Hey, nice work! Sorry for the duplicate issue. You have enough to do poking around inside Trizbort.
