### ISSUE TITLE
Trivial fidelity: text overlap in labeled lines to/from ellipse rooms (8 cardinal directions)

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#109]
(Seen 1.5.9.2, been around since rounded edges)

A test file will be coming of all the angles at which you can connect ellipse style rooms. In some of them, the "end" text is covered up. This issue may need to be broken up, but since I have a test file, hopefully this will be easy to visualize.

Rounded edges work okay.

**Comment by JasonLautzenheiser** [comment]
#261
