### ISSUE TITLE
Explicit exit markup in script files

### ISSUE THREAD

**Issue by matthiaswatkins** [JasonLautzenheiser/trizbort#11]
It would be useful to have a script command, something like 'trizbort exit north' that would tell the automap that there is an unmapped or blocked exit to the north that would warrant further exploration later. Maybe also 'trizbort noexit north' to have the automapper delete erroneously detected exits.

**Comment by andrewschultz** [comment]
I like the idea of starting trickier commands with TRIZBORT. Being able to delete/allow exits seems really useful. I don't know if Trizbort picks up "There's a wall to the north" as an exit north, but Genstein's docs do say it only does so much and could use some help. So this sounds very good in the big picture.

I'd also be glad to verify any of this sort of issue, especially if you provided a test case.

**Comment by matthiaswatkins** [comment]
The automapper picks up any exit word in the room description. It very often erroneously detects 'up' because up is commonly used in other contexts. It would detect "There's a wall to the north" as an exit north. This isn't a really big deal because if you try to go north and fail, the automapper will delete the erroneous exit. Then again, if you try to go through a locked or closed door and fail it will also delete the exit, which is why it would be helpful to have the ability to force exits in transcript.

I'm happy to put some time in on the automap code, since that's most of what I use trizbort for.

**Comment by andrewschultz** [comment]
Awesome--this would work really well, since it hasn't been what I've focused on in my testing and feature requests. I didn't know if anyone really used it. I generally just created maps by hand. But if you get the automapper working smarter, I think that could be a big selling point.

**Comment by JasonLautzenheiser** [comment]
I'm all for it too...it's an area I've not really dabbled too much into the code.  Feel free to make changes and put a pull request up.  It would be much appreciated.

**Comment by andrewschultz** [comment]
[automap-force-dir-example.txt](https://github.com/JasonLautzenheiser/trizbort/files/45373/automap-force-dir-example.txt)

I think this is a good test document to see how to implement this feature. Now that I've poked at the automapper code a bit, I feel more comfortable with it.
