### ISSUE TITLE
Trivial fidelity: text overlap in labeled lines to/from ellipse rooms (8 minor directions)

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#110]
(Seen 1.5.9.2, been around since rounded edges)

A test file will be coming of all the angles at which you can connect ellipse style rooms. In some of them, the "end" text is covered up. This issue may need to be broken up, but since I have a test file, hopefully this will be easy to visualize.

The file name is (or will be) ellipse-to-from-16ths.trizbort.

This is not as critical as #109 as few people use the other ports. So I think it should be broken up that way.

Rounded edges work okay (rounded-to-from-16ths.trizbort).

**Comment by JasonLautzenheiser** [comment]
#261
