### ISSUE TITLE
Error checking: request for warning box on unsuccessful smartsave

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#121]
1 create a new file
2 ctrl-shift-s
3 yes
4 hit escape

Note that there is no useful warning reminder as from
1 create a new file
2 ctrl-shift-s
3 no

This would be nice to have but probably sticky to program.

**Comment by JasonLautzenheiser** [comment]
Which warning box are you talking about?  I'm not completely sure I'm going through the same process as you are as I'm not seeing where the issue may be.

**Comment by andrewschultz** [comment]
I said ctrl-alt-s, but I meant ctrl-shift-s. I updated the issue to reflect that. Sorry for the confusion.
