### ISSUE TITLE
Feature: label room as initial?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#125]
This could be a nice tweak if we want to export code. It could also allow us to go back to this room or have it as a bookmark. The letter I could note it as the initial room, and ctrl-i could go back to highlighting it.

However, people may create the first room in their game first anyway, so this may not be very practical.

**Comment by JasonLautzenheiser** [comment]
This is an interesting thought....and perhaps it's more than one feature request, but I could see bookmarks being handy here (with perhaps a default one being the first room created)....but also in the export, have a way to mark the room as the start room in game.

**Comment by JasonLautzenheiser** [comment]
The user can now select the starting room (it will export appropriately to I7 & ZIL, but not other languages yet).  It denotes the starting room on screen with a light green highlight around the room.  You can change it in the room settings and there is only allowed one starting room.
