### ISSUE TITLE
failing to write to PNG file mistakenly gives success in smart-save popup

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#127]
1. create a simple file called access.trizbort. Save it.
2. ctrl-shift-s to smart-save as PDF and PNG.
3. from a DOS command line, attrib +r access.png
4. ctrl-shift-s again. Trizbort acknowledges that the PNG write has failed, but then it says both PDF and PNG files exported successfully.

Is Trizbort just searching for any PNG file (or whichever) before saying it exported successfully?

**Comment by JasonLautzenheiser** [comment]
This was fixed with #129
