### ISSUE TITLE
Failed EMF export does not generate error

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#128]
1. create a file called locked.trizbort
2. set the export graphic type to EMF in Tools::App Settings (Alt-T, A, D, E)
3. smart-save
4. on the command line, attrib +r locked.emf
4a. you may wish to add a room to verify that the map can/should be bigger
5. smart-save again.

Note trizbort says it is successful even though it is not.
dir locked.* can verify the file size of locked.emf is still the same.

BMP/JPEG/PNG give a popup saying a generic GUI error occurs, but EMF does not.

**Comment by JasonLautzenheiser** [comment]
EMF files are saved in a completely different way so different checks had to be made.
