### ISSUE TITLE
Add "about" to I6 exported code

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#131]
Jason, I'd like to try and make this fix since it's a really minor thing & I'd love to have experience writing up C# code and contributing it to a repository. Would that be okay?

The code to add is as follows:

Verb meta 'about' * -> About;

[ AboutSub ;
  print "(the history string)";
];

**Comment by JasonLautzenheiser** [comment]
Sure, go for it and post a pull request.

**Comment by andrewschultz** [comment]
I've fixed this, and it's a case where I'm 99% sure it works well. I'm willing to take a bit of heat if it doesn't--I haven't figured how to compile I6 code yet, but I'm imitating verb creation structure I've seen in other I6 code.
