### ISSUE TITLE
Deleting region doesn't revert its ex-rooms to NoRegion

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#132]
Any file with regions works, but https://raw.githubusercontent.com/andrewschultz/stale-tales-slate/master/Shuffling/shuffling-around.trizbort can reproduce it easily.

Test case:

1. open your file
2. Tools:Map Options::Regions
3. delete the Forest region. Notice the green turns white.
4. right click on any of the ex-green rooms and try to set the region. Note they are not assigned to "NoRegion," e.g. there is no box around the white square. The Trips Strip, however, is.

You can also open a trizbort file saved after you delete the region and note that, say, Frost Forts has region="Forest".

I'm 10% worried this has been reported before even though I looked for it in the issue tracker. So again, if this is a minor enough issue, I'd be willing to take it up.

**Comment by JasonLautzenheiser** [comment]
I took a quick look and this should be minor enough if you want to take care of this one.

**Comment by andrewschultz** [comment]
Thanks, Jason! This is fixed locally, although I'm worried my code could be a lot cleaner.
