### ISSUE TITLE
Feature: ALAN export?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#138]
This is low on the list since ALAN is pretty obscure, but it might be a good programming exercise, or a good example for creating templates.

**Comment by andrewschultz** [comment]
Well, a user wants it! So I'd be willing to push this through.

Page 26 of http://www.alanif.se/downloads/documentation/manual.pdf for later notes.

**Comment by JasonLautzenheiser** [comment]
I say go for it.....just out of curiosity, where did you see the user requesting this?

**Comment by andrewschultz** [comment]
Private email. He mentioned "Hey, there's this neat freeware mapmaker" and he linked me to Genstein's site. Then I pointed him to Trizbort.com, and he said too bad there's no Alan export, he would use it.
