### ISSUE TITLE
Export I6/I7/TADS to Notepad instead of saving to disk

### ISSUE THREAD

**Issue by vaughany** [JasonLautzenheiser/trizbort#14]
I've used the 'export to I7' option before (as I use Inform, but this applies equally to all exporting options, I believe), but after the first save, I don't necessarily want to overwrite the `story.ni` file (or save it in another location) as I may have worked on it already. 

So one feature I'd request is instead of exporting I6/I7/TADS source to an appropriate file, export the code to Notepad (or more properly, the system's default text editor) instead. This way, I can copy/paste snippets into my existing projects without having to save another copy of the code to disk unnecessarily.

**Comment by andrewschultz** [comment]
Hmm...I think I've thought of something like this, too. To clarify, do you mean cutting/pasting to a new unnamed temporary text file then opening it in the default editor? Or just cutting/pasting to the clipboard? Either would be useful.

I agree that exporting to a file risks overwriting & it's confusing to deal with several similar files in the same directory.

It seems like a setting for exporting source to clipboard, a regular file or a temp file wouldn't be *too* bad. I also wouldn't mind the opportunity to open a snippet/file immediately after exporting.

So in an ideal world I'd have

(1 of 3 options) export to file | export to temp file | export to clipboard
open file on export or not (not valid with export to clipboard)

But that gets a bit lumpy on the programming side.

**Comment by vaughany** [comment]
As you say, either saving to a temp file and opening in [editor], or saving to the clipboard would be useful (alongside the existing options). I think the temp file/open in editor option would be more useful as I could then choose what to copy and paste into my story (assuming I have added to a previous map and just want the new bits), but either is fine.

**Comment by vaughany** [comment]
While I think about it, the exporting to I7 option had me slightly confused. The first time I came to export to Inform 7, it asked for a save location and a name, which I supplied, and the generated I7 code was saved without problems. However next time I came to export the same map (after adding some new rooms and connections and such), I couldn't simply overwrite the existing exported file, I had to either 1) export with a new name, creating a new set of folders e.g. [name].inform unnecessarily, or 2) open the [name].inform folder, then the Source folder, then choose the story.ni file to be overwritten.  

I enjoy that Trizbort created the necessary folders, but I suppose what I am saying is that on subsequent exports, it should maybe be able to export straight into the previously exported file. (Actually, the graphics program GIMP does this rather well: it has an export option, and a separate 'overwrite' option that literally overwrites the previously exported file with a new one without needing to choose folders, names etc.)

I guess I have gone some way to explaining my reasons behind opening this issue! Sorry if it's a bit log-winded, I'm not often as concise as I'd like. :)

(And thanks for your welcome!. :)

**Comment by JasonLautzenheiser** [comment]
The export for I7 confused me as well at first because of it creating the entire structure by default.  You can change the file type in the file dialog to be just the NI file, then you can overwrite it like normal.  I tend to do like you where I'll map, export to just the NI file and then open it up in text editor, copy what I want into Inform and then repeat as needed.

I do like the basis of this feature and I don't think it would be that difficult to add a feature for opening up in your default text editor.

**Comment by JasonLautzenheiser** [comment]
I updated the repository (ef69b9728b3013e2f0d1517b37ddb118290101c8) to include the ability to export the source code (in whichever language) to the clipboard.  I choose the clipboard as it was the least obtrusive to the user (just a simple keystroke or menu item selection, no settings to set) and allows for maximum flexibility (I don't presume that you want to open it in a text editor or something else).

**Comment by vaughany** [comment]
:+1:
