### ISSUE TITLE
exception on creating 2 rooms from orphaned lines

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#142]
To follow up on P1NG's earlier bug #101 I found the following

1 create a new file. R, ctrl-right, R.
2 unhook the connector from each room.
3 highlight the connector and push R
4 highlight the connector and push R again

You get an exception the second time.

**Comment by JasonLautzenheiser** [comment]
The exception is removed....but needs more smarts to placed rooms properly.  Keeping this open for now.
