### ISSUE TITLE
override darkness size in ellipse if darkness tab is outside the bounds

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#146]
With the new ellipse shapes we now have a problem if the darkness tab is not visible. One size does not fit all any more.

If we start with the defaults, create an ellipse room, and pull it 2 down and 2 right, the darkness tab is not visible, because the corner cuts it off.

So we need a check. This is some awful arithmetic involved, and it's doable. But I don't know if it's practical.

**Comment by JasonLautzenheiser** [comment]
Also happens with the octagon

**Comment by andrewschultz** [comment]
This might be a good time to decide what to do in general.

The octagon is going to be a problem as long as the dark tab is necessarily isosceles, because if we have a wide shape or a tall shape, the tab will be partially cut off.

This looks like something else that wants/needs a few extra tweaks. Because different rooms can be different sizes, it might be helpful for some shapes to define the dark tab size as a percentage of the height/width.

For rounded corners, I don't think we can do anything other than to and make sure that its darkness tab size is at least 1/2 of the upper right curvature. I haven't had a chance to look into the rounding formula, but it appears a darkness of 12 and a curvature of 30 means the darkness tab just shows up. 15-20 makes the tab pretty clear without being obtrusive.

For octagonal corners I think having 35% of the X- or Y-distance from the center is good. I have set the octagon vertices 25% of both the x- and y-distance from each rectangle corner.

This is another issue I think would hit my strong points because I like mucking with numbers. But I want to make sure what I am saying makes sense.

The minimum percentage for an octagon is 25.
