### ISSUE TITLE
Eliminate cornerTop* parameters in XML if roundedCorners=no/allCornersEqual=yes?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#150]
It seems like we set the default to 15 in any case.

public void Load(XmlElementReader element) in Room.cs could go... 

if (element.Attribute("roundedCorners").ToBool()) { Corners.TopLeft = element.Attribute("cornerTopLeft").ToFloat(); } else { Corners.TopLeft = element.Attribute("cornerTopLeft").ToFloat() = 15; }

So we could keep the important information in the XML & also delete a few lines in public void Save.

Also allCornersEqual = "yes" could go

Is this cutting corners? I don't know how to balance "XML can track everything" vs readability.

Similarly if allCornersEqual="yes" then is it getting too cutesy just to say cornerTopLeft=15 and ignore the others?

**Comment by JasonLautzenheiser** [comment]
Sure we could probably get fancy with it and clean up the XML, but in reality, I'm not too worried about the readabilty of it as I suspect with just a few exceptions, no-one ever looks at it.  So I may err on the side of less logic to build it (meaning less chances to screw it up)

In V2 I have thoughts on changing the file completely as the code to save / load is actually needlessly overly complicated.
