### ISSUE TITLE
GetAngleInRadians is not used by any other functions: others?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#154]
While I could just delete it and commit, because CalcRadianForEllipse is a lot slicker, I am wondering:

1) could it have any other use?
2) is there any code-reading program that could determine what other functions aren't used/are orphaned, sort of like how the C# debugger knows code is unreachable/local vars aren't initialized/used??

**Comment by JasonLautzenheiser** [comment]
@andrewschultz I removed the function as it's not being used.   I use Resharper (https://www.jetbrains.com/resharper/) and have for years.  Not free, but worth every penny.
