### ISSUE TITLE
OnKeyDown in Canvas.cs could add # keys to Keys.(Right/Left/Up/Down)

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#166]
The code in question: (line 1058)

        case Keys.Right:
        case Keys.Left:
        case Keys.Up:
        case Keys.Down:
          switch (ModifierKeys)

Keys.NumPad* are listed further down but seem out of place. (line 1260)

We'd need to make a few changes elsewhere. ctrlArrowHandler would need an expanded switch statement, which we might want to expand to a function since it could be useful elsewhere. But it would be nice to have numpad keys functionally equal to arrows.

**Comment by JasonLautzenheiser** [comment]
The numlock key takes care of making the numberpad work like the arrows...so I'm hesitant to add any code as it can already be done.

**Comment by andrewschultz** [comment]
I forgot to mention the main reason I wanted to look at this--it would be nice to have Keys.Numpad(1/3/7/9) is with this case statement, because diagonal directions are treated a bit differently from regular directions. Programmers might need to write the same code twice.
