### ISSUE TITLE
trivial mapstats add: dark rooms?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#167]
With a release pending, feature creep is a very bad thing. But would this code be safe/desirable to slip in? It seems low risk but can obviously wait, and I can just add it locally for my own projects.

MapStatisticsView.cs:
      stats += $"# of Dark Rooms: {MapStatistics.NumberOfDarkRooms}{Environment.NewLine}";
after # of Rooms (or anywhere)

MapStatistics.cs:
    public static int NumberOfDarkRooms => Project.Current.Elements.OfType<Room>().Count(p => p.isDark);
after NumberOfRooms.

**Comment by JasonLautzenheiser** [comment]
Looks good, though you forgot the type on OfType...line should be like .
Feel free to add it in.

MapStatistics.cs:
public static int NumberOfDarkRooms =>
Project.Current.Elements.OfType<Room>().Count(p => p.isDark);

**Comment by andrewschultz** [comment]
Thanks! This has been very helpful to me, because I've used dark rooms as flagging whether I'd implemented anything in there or not. (I think this is the sort of note I'd like to include in the docs.)
