### ISSUE TITLE
Connector words carried to new file while format is not

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#169]
1. create a file. Push R to make a room.
2. type I, T and A.
3. right arrow. Note the line is dotted, arrowed and has "in/out."
4. Now create a new file. Ctrl-n, don't save.
5. R, right arrow.

Note that the in/out text is preserved but the dotted and arrowed formatting are not. It seems like they should be all be consistent, though this is hardly critical (and totally deferrable of course) since we can type P to make the connector plain.

**Comment by JasonLautzenheiser** [comment]
I agree that it should be consistent....I'm inclined to say though, when creating a new file, the defaults should be set and nothing carried over.

**Comment by andrewschultz** [comment]
This was part of the whole raft of code changes I put into that one big code request. If you'd like, I can go through issues like these that look closeable to untangle things a bit so we can close a few issues with the 1.5.9.4 milestone. I'll let you push the button, but I will do the poking around.
