### ISSUE TITLE
Can S (or 0) send the user to the start room?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#170]
I don't believe it's been used yet, but it would be a neat navigational trick.

Again, almost certainly too close to release to add it, but the thought struck me as I was twiddling my IFComp game map where the starting room is not really in the center.

S might be too close to the saving commands, but it'd be neat to have something.

**Comment by JasonLautzenheiser** [comment]
I kind of like the 0, since it could signify the "genesis" of the game.
