### ISSUE TITLE
Can we specify an end room too?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#171]
THe green halo start room has been a big help, enough that I'm going to get greedy and ask for a red halo end room. This might, however, make the room property GUI crowded.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz Some questions on this.  

* Would you be able to have multiple end rooms?
* Is this purely for visual in the map or would there be some sort of export involved here? (I can't think of anything)

I'm not too worried about the Room Properties page, we can rearrange to make room if it's something we want to do.

**Comment by andrewschultz** [comment]
This is strictly aesthetic for the moment. However, I'm thinking that there's a use case I'm missing where it'd be handy and practical.
