### ISSUE TITLE
Create preferences (merge & expand on App Settings)

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#174]
As I think of this (or issues like #93), I realize that while we have some settings in the app settings, I'd like to create some default settings that will always be loaded when either creating a new file or when first loading the app.....For example, I prefer not to have the hand-drawn on, but need to turn it off each time.  Or let's say I always want to default to a room with rounded corners (and a specifc roundedness).   Currently Trizbort is weak in this area.

I'll take some time to review each feature and see if it makes sense to create an app-level preference to it

**Comment by andrewschultz** [comment]
This would not be too bad to test. Let me know if you want a spreadsheet of all the features. I agree it'd be great to move as much as practically possible to app settings. (I also prefer not hand drawn.)

**Comment by andrewschultz** [comment]
Hm, this might be too much to pile on to #65, but I was wondering if the following GUI would work:

App settings:
add "hand-drawn by default" and "Default room shape" at the bottom

Project settings:
add default room type next to "hand-drawn" checkbox

Room settings:
add "hand-drawn" for individual room in the final tab where we can change if something is hand-drawn. Maybe add an accelerator for ctrl-d to toggle hand-drawn status.

This would eliminate the problems the StraightEdges variable causes.

I would need to test cut/pasting as well as other things (I remember this bug from making Octagonal rooms,) but I'd be willing to do any extra testing here. I think now that we've put in margins and default font, it's all a bit easier to add, and I think these 4 options being app- and project-level would be a good base for this issue.
