### ISSUE TITLE
Documentation for automapping seems out of place in the content heirarchy

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#18]
Right now, the **Using Automapping** section is under **Keyboard Fu**.  It seems it probably should be it's own main section under **Advanced Topics**

**Comment by andrewschultz** [comment]
I agree. I'll try to take care of this tomorrow.

**Comment by andrewschultz** [comment]
This is fixed locally--I just want to make sure the first merge is okay before sending the next chunk in, since it overlaps with the first merge.
