### ISSUE TITLE
IDE debug tests confuse the automapper.

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#180]
compound.txt has

> [1]

> [100]

And this causes everything to be east/west of each other.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz I'm not sure what this is about?

**Comment by andrewschultz** [comment]
@JasonLautzenheiser if I run a test in the Inform IDE, the text output is a bit different.

For instance, the text below isn't processed. Trizbort doesn't understand West is the direction.

>[181] w

Judgment Pass
With Officer Petty out of the way, the Intuition Counter is now just an inconvenience.

>[182] w

======================

Instead of, in-game,

> w

Judgment Pass
With Officer Petty out of the way, the Intuition Counter is now just an inconvenience.

> w

So I think the issue boils down to replacing the regular expression

> *\[[0-9]+\]

with >

Wherever the automapper does that.

This only happens with Inform IDE tests, but it'd be nice to be able to cut/paste text from there and see how it looks. As-is, Trizbort gets a bit lost.

=====================

This solution works but maybe we can do better:

        if (word[0] == '[')
        {
          for (var temp = 1; temp < word.Length; temp++)
          {
            if (word[temp] == ']')
            {
              stripWord = true;
              break;
            }
            if ((word[temp] < '0') || (word[temp] > '9')) { break; }
          }
        }

above

        if (stripWord)
        {
          continue;
        }

in Automap.cs.

**Comment by andrewschultz** [comment]
[quick-dir.txt](https://github.com/JasonLautzenheiser/trizbort/files/44600/quick-dir.txt)
[quick-dir-2.txt](https://github.com/JasonLautzenheiser/trizbort/files/44601/quick-dir-2.txt)
