### ISSUE TITLE
Feature: trim recursive-port connectors

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#181]
I ran automapper on Scroll Thief. The result is attached. Hall of the Mountain King is the one with the most connectors that go back to the same ports they came from.

Can we either 1) add an option to trim these ports in the gui or 2) make it an option in the Automap settings?

(Note: I can't upload files right now, but poke me if you need an example. It basically need a room with a description "You are blocked in all directions.")

**Comment by JasonLautzenheiser** [comment]
This can be handled with the select special -> self self-looping connections, then deleting them if need be
