### ISSUE TITLE
differentiation tool (looks like a potentially big feature)

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#183]
It would be nice to see differences between two versions of files in the context of Trizbort. For instance, I had a file I cut 15 rooms from, then I modified something in the new file, and I wanted to check if I'd modified anything more.
- What rooms are different?
- What connectors are different?
- What objects are different?

This is probably impractical with files too different from each other, but even being able to compare a file's new version to its old version can be a help.

NOTE: there's a strong possibility this is way too much work. If so, could you redirect it as a documentation feature? A 3rd-party way to check this is to download WinMerge and compare 2 trizbort files. That worked in my situation, because Trizbort doesn't shuffle room IDs etc around, and I'd like to add that, with the caveat that adding/deleting too many rooms may make things useless.

And while the docs can't give overarching views on backing things up, some Trizbort specific tips would be nice.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz I think documenting the 3rd party way would be a good idea.

However, this has got me thinking about this feature...you're right, this would not be trivial to implement, but would be interesting and potentially useful for more than just comparing differences on maps
