### ISSUE TITLE
feature: "save and back up?"

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#184]
Maybe ctrl-b could, if the file is named a.trizbort, back it up the current version to a-backup.trizbort before saving to a.trizbort.

If that's taken, a-backup-1.trizbort, etc. A popup box would verify the backup file name.

This isn't terrible to do manually, but it's a nice safeguard for when I want to try experiments.

**Comment by JasonLautzenheiser** [comment]
Implemented in c45ffb1
