### ISSUE TITLE
Feature enhancement: TADS/Adv3Lite may support regions now

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#185]
http://users.ox.ac.uk/~manc0049/TADSGuide/adv3Lite.htm indicates it does. If so, I think it would be useful to add, along with commented code saying regions need Adv3Lite. I'm playing with this, but I may not have time/motivation to fix it fully.

**Comment by andrewschultz** [comment]
There are a few issues here. I managed to export regions to TADS 3 on my local version of Trizbort. It's a relatively simple fix. But regions are only supported by Adv3Lite.

I think the best way to go would be to allow the user to toggle an option between Adv3Lite and regular TADS. I would be willing to provide minimal documentation. I think this would also allow us to make use of the "Inform 7" tab that is hidden currently from the end-user when I open up AppSettingsDialog.cs. It might need to be changed to "language specific" or something. Then a TADS sub-region could have an option called "use Adv3Lite."

The only problem is that I'm not able to edit that dialog reliably via the Designer in Visual Studio Community 2015, and I'm sure I'll make a mistake if I edit it manually. If I add a checkbox, it's added to both the General and Inform 7 tabs.

I'm able to click and switch tabs on RoomPropertiesDialog.cs easily enough when I open it in the designer, but not AppSettingsDialog. Assuming this is a desirable fix, what do I need to do?

![tads3changes](https://cloud.githubusercontent.com/assets/6201356/10654565/ae059bac-7831-11e5-928d-2c64cc37ce2b.png)

**Comment by JasonLautzenheiser** [comment]
Unfortunately, I believe that tab control is part of the dotnetbar library, which is commercial, so you may not be able to edit that without a license.  

I was planning on reworking the tabs on that form and the others anyway soon, but in the meantime, I would just throw the option on the general tab and we can move it later.
