### ISSUE TITLE
Feature enhancement: Hugo regions and other tweaks

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#186]
Mail from Jonathan Blask (edited to focus on the technical bits)

In the code generated for me, there are spaces in "# include", "# ifset", and "# link" that'll prevent the code from being compiled.
My "init" routine ended with a ; instead of a }
Really, you don't even need to do that PRECOMPILED_LIBRARY stuff.  Nobody these days is going to use that.  You can just have "#include hugolib.h"
Hugo files also require a "main" routine and, ideally, declare a player_character and init should set the player global to it.

Now, this brings us to the question about whether the code Trizbort supplies really needs to produce entirely-compilable code or whether it should just produce a file easily includable to an existing shell.  It could just have a commented note like the following:

    ! copy and paste this code or #include this file to add to your game

If you feel strongly that it should be a compilable file, I've included a couple examples.  "bare.hug" is a minimized version of the bare-bones shell I use for my games, while "stripped.hug" is cut down as much as can be.

Lastly, if the other languages supported have code for handling regions, I would suggest generating something like the following for Hugo games:

    property region  ! only needs to be declared once

    class rockyarea   ! make a class object for the region

    {

    	region rockyarea

    }

    room rockyarea1 "Rocky Area"

    {

    	inherits rockyarea  ! apply the class to rooms in that region

    }

 
This way, any rules applied to the class object gets applied to every room in that region.  It also allows for checks like "if location.region = rockyarea".

(I'll attach other stuff later.)

**Comment by JasonLautzenheiser** [comment]
I can start taking a look at this.  When you get a chance can you send along the files he attached?  Especially the minimal hug files he mentions?

**Comment by andrewschultz** [comment]
Sorry for the delay. I got caught up in other things.

https://gist.githubusercontent.com/andrewschultz/eafc2d9913686198bd07/raw/0831edcd174cba4b960e9769e31d6140bb0a2191/stripped.hug

https://gist.githubusercontent.com/andrewschultz/b83ed035c2af78682868/raw/1a77aade56f09059eb4253b7c32199ffe15fcae8/bare.hug
