### ISSUE TITLE
Feature: accelerators to auto-reorg connector ports.

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#188]
This is a tricky one so I want to make sure it is sane before doing any work on it.

If 2 rooms are connected, and we move them, it can be tricky to move the connectors as well. It would be nice if they could be auto-aligned with a keystroke. Call it ctrl-backslash?

This organizer/auto-aligner would work as follows:

At least for the first version we would not use 16th-ports. Maybe we could add an option for that later.

Trizbort will detect if rooms were directly above or below or left or right of each other. It will calculate the center of the rooms.

If they match up vertically, use north/south ports.

If they match up horizontally, use west/east.

If the (absolute value of the) ratio of vertical to horizontal is between, say, 4/7 and 7/4, use the correct diagonal port.

There are problems if, say, the rooms overlap, but we can maybe error check that later.

**Comment by JasonLautzenheiser** [comment]
These seems like a reasonable solution....and what could be a nice feature.  

Maybe an optional setting that would enable this automatically when moving rooms, so the connection is automatically adjusted....this could be a different request.

**Comment by andrewschultz** [comment]
I have it so you can push ctrl-backslash and one highlighted rooms will adjust. (I worked on this when I was trying to figure that other error I haven't given repro for yet. I still need to get to those.) However, the "disappearing" port bug I just reported still appears. In fact, it's glaringly obvious.

The feature is just for one room now, because I think it would be good to start small. But I agree a "readjust on drag" or "readjust after drag" would be useful. It might also be nice to avoid collisions, or warn on collisions, but that is tricky. It shouldn't really be a problem without a ton of connectors from/to one room.

The current code allows for granularity: you can choose to have only NSEW as available directions, or NSEW + diagonals, or all 16 directions.

```csharp
                switch (Settings.AdjustGranularity)
                {  //These numbers are decided as follows: tangent of 45 degrees, then 22.5/67.5, then 11.25/33.75/56.25/78.75
                    case 0: //fourths
                        if (abSlope > 1) { cp = CompassPoint.North; }
                        else { cp = CompassPoint.West; if (isLeft) { cp = CompassPoint.East; } }
                        break;
                    case 1: //eighths
                        if (abSlope > 2.414) { cp = CompassPoint.North; } //incidentally tan (pi/8) = sqrt 2 - 1. Angle bisector theorem/trig identities prove it if you're wondering.
                        else if (abSlope > 0.414) { cp = CompassPoint.NorthEast; if (isNeg) { cp = CompassPoint.NorthWest; } }
                        else { cp = CompassPoint.West; if (isLeft) { cp = CompassPoint.East; } }
                        break;
                    case 2: //sixteenths
                        if (abSlope > 5.03) { cp = CompassPoint.North; }
                        else if (abSlope > 1.49) { cp = CompassPoint.NorthNorthEast; if (isNeg) { cp = CompassPoint.NorthNorthWest; } }
                        else if (abSlope > 0.668) { cp = CompassPoint.NorthEast; if (isNeg) { cp = CompassPoint.NorthWest; } }
                        else if (abSlope > 0.197) { cp = CompassPoint.EastNorthEast; if (isNeg) { cp = CompassPoint.WestNorthWest; } }
                        else { cp = CompassPoint.West; if (isLeft) { cp = CompassPoint.East; } }
                        break;
                }
```
