### ISSUE TITLE
Automap feature: force dotted connection

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#196]
Consider the following transcript:

============================

Three Rooms
A Trizbort Automap Test File by Andrew Schultz

Along the Road

>trizbort force dotted

>w

Outside the Cave

>e

Along the Road

>
It would be neat, as in #11, to note that a passage was dotted so that we would know it required a puzzle etc.

**Comment by andrewschultz** [comment]
I'm not sure what I did here, but Visual Studio 2015 doesn't like it at all.

In fact, I am pretty sure I am missing something fundamental about C# that I am somehow violating threading.

Above "we should just have one word left" in automap.cs:

      if (words[1].Equals("dotted"))
      {
        m_useDotted = true;
      }
	  
Causes an execption. I've tried to define

    private bool m_useDotted = false;
	
and the public variable, but I can't get it to work.

in the function void IAutomapCanvas.Connect, this works okay:

      if (m_automap.m_useDotted)
      {
        connection.Style = ConnectionStyle.Dashed;
        m_automap.m_useDotted = false;
      }

But the problem is when I try to change m_useDotted in Automap.cs. I'm confused about this. Where do you recommend I learn about regions, etc.?

**Comment by JasonLautzenheiser** [comment]
What's the exception you get and on which line?
