### ISSUE TITLE
Add option to auto-load the last saved map when opening trizbort.

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#202]

**Comment by andrewschultz** [comment]
Oh, hey, that's a great idea. I can see what to add to the code & where. Will/can you take this one or should I? (I am planning to send in a small automapping test suite along with margin testing files, so another commit would be no problem.)

**Comment by JasonLautzenheiser** [comment]
I might not get to it for a few days at the earliest, so if you want to do it feel free.

**Comment by JasonLautzenheiser** [comment]
In addition to the command line parameter (which I think is great), I was thinking of having an application setting that would do this automatically anytime you open Trizbort (not just from command line)

**Comment by andrewschultz** [comment]
I agree. This isn't trivial, as I think we should override this setting if we write, say, trizbort my-map.trizbort, but I think it would not be hard to hash out.

**Comment by JasonLautzenheiser** [comment]
Yes, command line parameters would override any default settings that may
be set and used through normal opening.

**Comment by andrewschultz** [comment]
Ok, the override in the app settings is now in place. MainForm.cs has changes which check to see if a project has been loaded. If so a boolean is set to true. If it is true, we don't open the default at the end of MainForm_Load.
