### ISSUE TITLE
Making a testing folder?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#21]
I'd really like to make a testing folder here. Maybe this is too ambitious, but here are my thoughts.

The folder could contain both transcripts and game procedures for automapping. And it could also have TRIZBORT files (or a zip containing them) along with a small test procedure document. These would mostly be unit-testing, at least to start. For instance, room_fill_examples.png and border_styles.png both come from basic unit test files, but we could do more, such as font name or color testing.

**Comment by JasonLautzenheiser** [comment]
I think it's a good idea.  Not only would it help verify changes, but also give users some examples for features as they come out.

**Comment by andrewschultz** [comment]
Before closing this I still need to decide the best way to write a test plan, or if I need to.

1. openoffice (flexible but can't be linked from Docs directory)
2. HTML
3. self-documentation in the batch file about what we should see, since the batch file opens 1 trizbort file at a time (doesn't allow for more detailed comments e.g. that the user should feel free to take what they want from the test files by copy/pasting or whatever if it saves them time)

An example of 3 is below:

echo Version testing here. All the files should look the same except if I explicitly mention new features are added.
echo The files aren't perfectly identical. Their trizbort versions are different.
c:\Users\Andrew\Documents\GitHub\trizbort\testing\basics-1570.trizbort
echo (skipping 1571-1586 for brevity here)
c:\Users\Andrew\Documents\GitHub\trizbort\testing\basics-1587.trizbort
echo All 6 border types appear below.
c:\Users\Andrew\Documents\GitHub\trizbort\testing\borders.trizbort
echo Connection types and combinations are tested here.
c:\Users\Andrew\Documents\GitHub\trizbort\testing\connections.trizbort
echo All 9 room type fills are tested here. The center is blank. They should form a white octagon.
c:\Users\Andrew\Documents\GitHub\trizbort\testing\fills.trizbort


These can be arranged later in order of priority later. But the batch file lets me F4 through them all. Does this look useful/good?

**Comment by matthiaswatkins** [comment]
You could use the wiki page here. Just click on the link to the right; anyone can contribute and create pages.

**Comment by JasonLautzenheiser** [comment]
yes Wiki would be good.  Feel free to create any page(s)

**Comment by andrewschultz** [comment]
OK, got basic stuff done, so I can close this. Thanks both of you for pointing this out! I just never noticed the wiki.
