### ISSUE TITLE
font code name refactoring

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#214]
LargeFont, SmallFont and LineFont are slightly misleading names. They are not used that much, but it would be nice to change them to, say,

RoomNameFont, ObjectFont and LineSubtitleFont.

I don't think this would require changes in Trizbort files' XML, but if we wanted to be super-precise, I imagine it would not be bad to check 2 different tags for consistency.

Detailed explanations/data below. ===========================

Now:
		<fonts>
			<room size="13">Comic Sans MS</room>
			<object size="11">Comic Sans MS</object>
			<line size="9">Comic Sans MS</line>
		</fonts>

Possible changes (if we even need to):
		<fonts>
			<roomName size="13">Comic Sans MS</room>
			<object size="11">Comic Sans MS</object>
			<lineAndSubtitle size="9">Comic Sans MS</line>
		</fonts>

The if statements around line 1008 of settings.cs could be changed

        if (font.Name == "room")
        {
          LargeFont = new Font(font.ToText(LargeFont.Name), Numeric.Clamp(font.Attribute("size").ToFloat(LargeFont.Size), MinFontSize, MaxFontSize), style, GraphicsUnit.World);
        }
        else if (font.Name == "object")
        {
          SmallFont = new Font(font.ToText(SmallFont.Name), Numeric.Clamp(font.Attribute("size").ToFloat(SmallFont.Size), MinFontSize, MaxFontSize), style, GraphicsUnit.World);
        }
        else if (font.Name == "line")
        {
          LineFont = new Font(font.ToText(SmallFont.Name), Numeric.Clamp(font.Attribute("size").ToFloat(LineFont.Size), MinFontSize, MaxFontSize), style, GraphicsUnit.World);
        }

(Again, this opens up another can of worms with: do we want to flag warnings for deprecated XML? I don't think that's critical to this issue, and it might be more trouble than it's worth, but it may come up when, say, we redo the XML for room shapes etc.)

**Comment by JasonLautzenheiser** [comment]
Changed the code, but left the XML the way it is.  Not worth it to change at this point with possible breaking of old XML
