### ISSUE TITLE
trizbort does not recognize minor room option changes as project changers

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#217]
When we change some options, Trizbort does not mark the project as dirty.

    public bool RoundedCorners { get; set; } = false;
    public bool Octagonal { get; set; } = false;
    public bool Ellipse { get; set; } = false;
    public bool StraightEdges { get; set; } = false;
    public bool AllCornersEqual { get; set; } = true;
    public bool IsStartRoom { get; set; } = false;

For isStartRoom it looks like I need to do this in room.cs:

    public bool IsStartRoom
    {
      get { return mIsStartRoom; }
      set { if (mIsStartRoom != value) { mIsStartRoom = value; RaiseChanged(); } }
    }

    private bool mIsDark;

    private bool mIsDark;
    private bool mIsStartRoom = false;

This passes basic testing.

Is it worth any risks to fix the code so that these are marked?

Are there any options that are not worth changing? I don't want to start tearing up code just as an exercise.

**Comment by JasonLautzenheiser** [comment]
I think if somethings changes the state of the map then it probably should be marked as dirty....application wide settings (not necessarily map specific), would need to be.

**Comment by andrewschultz** [comment]
It turns out corner roundedness wasn't being noticed as a change, too, so I fixed that.
