### ISSUE TITLE
Change "granularity" settings to something less abstract

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#222]
I just don't know what, though. Fourths/eighths/sixteenths works, but it doesn't quite feel natural.

So maybe NSEW (4)/Diagonals (8)/All Ports (16)?

This would require tweaks elsewhere e.g. with ctrl-shift-backslash to alert the user.

Also is it worth changing the variable name Granularity to PortAdjustFocus? This isn't critical, but I think there are better names than what I originally chose.

**Comment by JasonLautzenheiser** [comment]
I agree...it took me a bit at first to really figure out what the "granularity" meant...not sure what the new wording should be, but I think it needs something.

**Comment by andrewschultz** [comment]
Here are some ideas:

PortSwitchDetailLevel?
PortSwitchLevel?
PortDetailLevel?
PortSwitchMode?
Port(Re)AdjustDetail?
