### ISSUE TITLE
Command line option to start automapping

### ISSUE THREAD

**Issue by matthiaswatkins** [JasonLautzenheiser/trizbort#23]
Start automapping from the command line with a specified script file, e.g. `trizbort curses.trizbort -a curses.txt`
* It might be nice to be able to specify an automapping configuration file as well.
* Or at least a separate option to be able to start processing from the end of the transcript.

**Comment by JasonLautzenheiser** [comment]
Andrew had actually suggested some command line parameters for processing a folder full of trizbort files and spitting out png's of them in a batch mode.  So I've begun looking at command line parsing and how best to automate some things in the code base.  I think this is a another good application for command line.

**Comment by andrewschultz** [comment]
I have code for this. I'm not sure it's totally robust, but I've managed to get it to run locally. My main problem is that I am able to save to a local file, but unless I close in the delegate() loop, Trizbort thinks it is dirty. I don't know enough C# yet to know what is going on, but currently I have

trizbort -m c:\games\inform\triz\automap-4-room-right-triangle.txt

Gives an untitled project

trizbort -m c:\games\inform\triz\automap-4-room-right-triangle.txt c:\games\inform\triz\out.trizbort

Will save and close to a trizbort file. (We can make an option to close automatically, but that's a bit later.)

**Comment by JasonLautzenheiser** [comment]
I can take a look at this deeper.  I have some other ideas for command line parameters as well.
