### ISSUE TITLE
accelerator to make current room description tooltip vanish?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#232]
Most of the time, tooltips are helpful, but no matter where we place it, it may get in the way of a connection.

Escape is already taken to change from highlighting a room to highlighting its ports, so maybe the reverse-quote would work if we implement this?

This is not critical since 2 alt-tabs are a quick turnaround. But if we can find a good key, it'd be a big help.

**Comment by JasonLautzenheiser** [comment]
Just a note...Escape doesn't highlight a rooms ports...it simply deselects any currently selected objects.    If your mouse happens to be over a room, it will show the ports on hover.

**Comment by andrewschultz** [comment]
Oh, that's handy. I didn't know that. But it makes total sense. I'll try and write that into my new documentation branch.

**Comment by JasonLautzenheiser** [comment]
#295
