### ISSUE TITLE
Migrate Settings to the System.Configuration namespace

### ISSUE THREAD

**Issue by matthiaswatkins** [JasonLautzenheiser/trizbort#24]
Do we know why Genstein hand-rolled this functionality? The Settings.cs file duplicates provided (and optimized) features of the System.Configuration namespace. It would be easier to parse, maintain, and update if it were standard.

**Comment by matthiaswatkins** [comment]
I'm happy to work on this Jason, if you think it's a good idea. Just assign it to me so we don't get cross-work.

**Comment by JasonLautzenheiser** [comment]
I'm not completely sure why it was done this way.  I've thought of moving it myself, just have never gotten around to it.

Couple things I think need done with this:
- Currently the settings.cs provides for **both** the application settings as well as the map settings.  These should be separated out as they are truly two different things.
- The application settings could be stored in the app.config.  I could see the potential for a lot more application style settings for better configuration.  You'll notice on the app settings form, I have a hidden Inform tab currently that will the the home of some Inform specific settings for outputting I7 code (formatting and such)
- The map settings, currently are stored in the trizbort file (along with the room / connection information).  I've thought about moving the trizbort file to a JSON format so I could use some serialization (json.net) to minimize code as well as to open up some vague ideas I've had on a web-based version (just some very loose thoughts floating through my head at the moment).   **But, perhaps for now we leave the map settings functioning how the do now and only tackle the application settings and split them out, saving the reworking of trizbort file settings to another day**
- Would be nice to keep the application settings backwards compatible, meaning if we see a settings.xml file out there, let's import those settings into our new configuration.

Thoughts?  

BTW:  I can't seem to assign this too you through githubs assignee feature, but consider the changing of application settings as yours.  We can discuss the trizbort map settings later.

**Comment by matthiaswatkins** [comment]
I agree that splitting out the two functions makes sense. I'll probably leave the application settings in the Settings.cs file (since that's the default that Visual Studio uses) and move the file saving stuff to a new class, but leave it untouched. I'll submit a PR after splitting then work from there to modify the application settings.

**Comment by matthiaswatkins** [comment]
That's weird regarding the assignee function. Can you just tag them as "Matt" or something? I'm happy to tackle any of the bugs that Andrew is finding as well, but I don't want to duplicate work.

**Comment by JasonLautzenheiser** [comment]
This will be handled with JSON settings file eventually
