### ISSUE TITLE
Modifying room with file created in 1.5.9.3 file throws exception

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#240]
This seems related to my fix for creating a default room.

Test case:

1. create a 1-room document in 1593
2. change the title (or anything)
3. open and save it in 1594

A quick fix is to force the room to straight edges, but that feels like a bit of a hack.

**Comment by andrewschultz** [comment]
This also opens up a bigger question: how much can/should we test modifying things with each change? Without having too many rules, it might be nice to have a checklist of small quick things to make sure nothing big broke, and this is one of them.

**Comment by JasonLautzenheiser** [comment]
We should come up with a list of things to regression test.  

In V2 I want to create unit tests to help with this.  I could create them now, but might put the effort to the next major version.
