### ISSUE TITLE
cut/paste of rooms+lines broken in 1584

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#26]
Cut/pasting more than 1 room + 1 line causes trizbort to seem to paste blank borders and room text.

Reproduction:

R, ctrl-down, enter to create 2 linked rooms.
ctrl-A, ctrl-V and observe the second room pair has no visible border or room text. Though if you click on them, you see the room text and that there is a solid border.

This seems more likely to occur with default colorings.

**Comment by JasonLautzenheiser** [comment]
This has been fixed....but it did expose a bigger flaw in the copy/paste code (and perhaps the internal object model at large)...the way the copy / paste is currently implemented it is difficult to add new properties and features that need copied....also extremely difficult to handle any kind of UNDO).  The copy/paste code will need rewritten I think.  Also need to look at the overall room/connection/project object model to streamline it even further (perhaps a vNext task)
