### ISSUE TITLE
diagonal connection annotations from elliptical get overlapped

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#261]
Test case:

1) r, ctrl-e to make an elliptical room
2) ctrl-numpad 7 to create a room NW
3) click on the connector and make each start/middle/end "abcdefg"

The text runs into the room. It doesn't do so for rectangular rooms or N/S/E/W connectors.

**Comment by JasonLautzenheiser** [comment]
Duplicates #378
