### ISSUE TITLE
ENH: Objects

### ISSUE THREAD

**Issue by PlNG** [JasonLautzenheiser/trizbort#269]
Shops, Items, Traps, Quests, and Locks. Maybe banks and storage lockers too.

Sometimes in Legends of Terris I have to deal with locks barring passages, and sometimes these locks are trapped, I'd like to be able to put these annotations|objects on connections. Here's an example.

    Before the Windswept Tower of Malruth
    This barren hill offers little shelter from the elements. A
    dark door stands closed, however there are two trapdoors
    leading up and down into the tower itself. Weeds surround the
    base of the tower.
    There is a locked door above
    There is a locked door below
    Obvious Exits: SouthWest
    Items here: Old telescope
    Ghost is offering a quest (use SHOW QUESTS)
    >search U
    Careful examination of the door reveals it has a Complex Lock, Dangerous Sleep Trap
    >search D
    Careful examination of the door reveals it has a Complex Lock, Dangerous Fire Trap

Liking the object syntax. I foresee many exciting possibilities there.

**Comment by JasonLautzenheiser** [comment]
I've long thought about putting attributes on connections to denote different things like doors, locks, staircases, ... I will definitely looking into doing something along these lines.

**Comment by JasonLautzenheiser** [comment]
I've added doors, #56 and the doors can be locked / opened /closed.  For now this will have to do.  I want to think harder about how to handle other cases, as they wouldn't be applicable in all cases or perhaps all cases....I'm thinking of allowing plugins for different items and languages.   But we shall see, something like that might require a big rewrite of trizbort.
