### ISSUE TITLE
Can we save app dimensions on close? (enhancement)

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#27]
While testing trizbort with my new batch script, it kept reopening at 632x477, which made it difficult to read the text etc. I tried to resize/maximize it but it kept bouncing back.

I think this would be useful for users in general, too. I know the size of the window I want depends on the map I'm using.

**Comment by JasonLautzenheiser** [comment]
Matt, while you are in there messing with the settings, would it be easy enough to go ahead and add this one?

**Comment by matthiaswatkins** [comment]
Yep, no problem.
