### ISSUE TITLE
Refactor command line parameter handling

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#270]
Refactor the command line handling to allow for more flexibile arguments.  Also allow for multiple commands to execute at once.

**Comment by JasonLautzenheiser** [comment]
This is related to #267 but wanted to break up that one task into multiple.  First needed to refactor the commands.

**Comment by JasonLautzenheiser** [comment]
#271

**Comment by andrewschultz** [comment]
Yeah. That issue was pretty sticky, and I think, good job breaking it up. I'm really excited to see where this goes--if you have stuff you don't want to deal with but think I could clean up, let me know.

**Comment by JasonLautzenheiser** [comment]
It still needs some cleanup.  The tricky party was working with the automapping in conjunction with saving it.   I'm not completely sure it was ever really working in the last release.  Because the automapping is threaded, it would never really finish mapping before it tried to do a quick save / close the app.  Thus the trizbort file that was getting generated was not complete.

Kind of a hack, but it made sense...for the command line automapping, we really don't need multi-threading, so I have an unthreaded section of code that it runs through instead...that way once the save hits, it's completed.

Overall, while still cleanup needed, I'm happy with the direction the command lines are going and with your suggestions in #267 I think this will turn into a nice tool that can run automated fairly well.
