### ISSUE TITLE
ctrl-k for force darkness?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#279]
This would be handy if we want to make all rooms dark, but it may be a bit limited. Still, I think it might be quickly doable with, or in place of, #278 if we wanted.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz I guess I'm a little confused on this and #278 on what the confusion is or what you are actually trying to do.  Is it if you have multiple rooms highlighted, in different states of darkness/light?  So hitting K will toggle them (dark become light and vice versu)?  

So then this Ctrl-K would be to force all highlighted rooms to dark regardless of their beginning state?   Maybe a Ctrl-Shift-K to force all to light.

Am I understanding correctly on this?

**Comment by andrewschultz** [comment]
Yes, that's correct. K only toggles all rooms, but ctrl-k would force them to all light or (ctrl-shift-k) to all dark. So if A and B were dark and C was not, and you highlighted them all,

K -> A, B dark, C light
ctrl-k -> all dark
ctrl-shift-k (as per your suggestion) -> all light

**Comment by JasonLautzenheiser** [comment]
Closed by #280

**Comment by JasonLautzenheiser** [comment]
@andrewschultz just merged this in....really simple change....got me thinking about a few other things that I can start cleaning the code up a bit too.
