### ISSUE TITLE
XML in object placement seems inconsistent

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#293]
Create a room with an object listed to the north.

XML = <objects at="n" custom="yes" customRight="12" customDown="12">Description</objects>

Create a room with an object to the south.

XML = <objects custom="yes" customRight="12" customDown="12">Description</objects>

Create a room with objects listed in the center.

XML = <objects at="wsw" custom="yes" customRight="12" customDown="12">Description</objects>

All but south and the center give valid directions. While it's understandable there are no directions for south/below( the default) and providing an odd direction for in the center, can we do better with either or both? I'd think we could have objects at="s" and objects at="center" respectively.

This also may be too much trouble to fix because we have to check backwards compatibility etc but it turned up while I wrote a few test files. (Note: the custom right/down doesn't seem to affect things)

**Comment by JasonLautzenheiser** [comment]
My thoughts on this is that while it would be an easy fix, the benefits may not be enough to warrant the risk of change and of backward compatibility issues or trying to accommodate backward compatability. 

Now having said that, I'm open for discussion on what the benefits would be as maybe I'm not thinking of something.

**Comment by JasonLautzenheiser** [comment]
While I could see this as a problem, I'm not sure the compatibility risks is worth the fix.  This would primarily be for people that looked at the raw source of the trizbort file, which I'm guessing is actually pretty limited.   There are a lot of other things I'd like to change with the format (perhaps even switching to JSON) that something like this could be cleaned up on if need be....but for now, closing this.
