### ISSUE TITLE
Allow automapper to assume bi-directional connections

### ISSUE THREAD

**Issue by dfabulich** [JasonLautzenheiser/trizbort#296]
Trizbort automapper assumes all connections between rooms are one-way. That's a very safe assumption, but it'd be nice to have a box I could check that would let it assume that connections are two-way, so I wouldn't have to double-track across connections just the sake of completeness.

Even better would be for it to assume that connections are two-way, but if it discovers that a particular connection isn't two-way, it could fix individual connections.

**Comment by JasonLautzenheiser** [comment]
#305 Added an option to assume two-way connections (on by default as I like that better anyways).  Will split out the second request into it's own task and I will look at that at another time.
