### ISSUE TITLE
trizbort.com makes documentation hard to find on narrow screens

### ISSUE THREAD

**Issue by dfabulich** [JasonLautzenheiser/trizbort#298]
Go to http://www.trizbort.com/ and resize your browser screen narrow (or visit on a phone-sized screen).

The sidepane of the page appears on the bottom of the page when the screen is narrow, making it very difficult to find the link to the Trizbort documentation.

I recommend moving the documentation link to the page header, right underneath the "View project on Github" link.

**Comment by JasonLautzenheiser** [comment]
Fixed
