### ISSUE TITLE
"Fill" in tools:map options seems obsolete

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#30]
I wasn't able to get this to have any effect even when starting on a new project, or creating a new region.

For instance, if you change the default room color, it appears in the next region. But the same doesn't happen for fill.

Repro:
Open map-settings-colors and create a new region. Note tools:map settings:colors and fonts has red fill and orange text, but a new region only gives orange text.

**Comment by JasonLautzenheiser** [comment]
Need to evaluate this.

**Comment by andrewschultz** [comment]
This is now used largely as the default region fill.
