### ISSUE TITLE
Room Properties window now opening in top-leftmost position on left screen.

### ISSUE THREAD

**Issue by AmberFennek** [JasonLautzenheiser/trizbort#309]
I suspect this is a new behavior, because I do not recall previously being so annoyed due to the Room Properties window always opening in the top left of the left-most screen.   My recollection is that it would appear somewhere atop the IF mapper window.

Could anyone verify this is a new (and annoying) behavior?  The window opens always in the far top left instead of in its previously positioned location.  I would not mind if the window became a tab of the main or docked on it somewhere, but I do dislike having it now appear in an inconvenient location.

My workflow suffers destruction. The land upon which I map is doomed.  Doomed!

**Comment by JasonLautzenheiser** [comment]
Hmmm.  I will have to take a look at that.  It shouldn't be doing that.  Thanks for the report.

**Comment by JasonLautzenheiser** [comment]
Latest commit should fix this.
