### ISSUE TITLE
Line text color has no effect

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#31]
The line text color in tools:map settings:colors and fonts has no effect.

map-settings-colors.trizbort shows this, and you'll also see the problem if you don't set the line color.

Repro:
1. create a new document with red line text
2 R, I, ctrl-right arrow

**Comment by JasonLautzenheiser** [comment]
fixed in 8eb5ace69beb0064ac7e7c3dc0d673caca7d5bfd
