### ISSUE TITLE
flip z-order of 2 rooms?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#315]
I wondered if this is practical or doable. I came up with a map scenario where one room was best put inside another (e.g. a phone booth in a big busy intersection.)

Trizbort orders rooms based on ID. This can be changed with a perl script I have.

Test case:
1. create a new file
2. create 2 rooms and have them overlap

If we switch their IDs in a text editor it works ok, but it's trickier when we have connectors. Should this be in trizbort, or should we just have side documentation?

**Comment by JasonLautzenheiser** [comment]
So really, file structure aside, what you really want is a z-order type of feature, where you can adjust the z-order of rooms?

**Comment by andrewschultz** [comment]
Yes, that is the good simple way to put it. It doesn't have to be complex, just, allow 2 rooms to swap z-order.

**Comment by AmberFennek** [comment]
I came across a circumstance where I also needed to change the Z-order. I manually swapped the name, description, and contents of the two rooms to do so.  Z-order in SVG, a similar drawing format, simply draws the objects in the order they are in the file.

**Comment by JasonLautzenheiser** [comment]
Added bring to front and send to back to the context menu to support this.
