### ISSUE TITLE
I6 exporting and accents

### ISSUE THREAD

**Issue by hlabrand** [JasonLautzenheiser/trizbort#329]
There's a problem in 1.5.9.6 with accents in I6 export : accented letters in the description or the printed name are replaced by '?' characters. This gives something like

Object etagere "?tag?re"
  with description "C'est une ?tag?re IKEA, achet?e hier.",
       name 'etagere';

Note that the name of the object, and the dictionary word, are as it should be, i.e. with the accented letter replaced by its non-accented version (probably thanks to the deaccent function?). However all the accents in the printed text are replaced by ?. To make it even more mysterious, the accents are absolutely fine if you select "export to clipboard" instead!

This problem does not exist for I7 Export, which works like a charm.

**Comment by JasonLautzenheiser** [comment]
Thanks for the report.   Any chance you can attach a sample trizbort file that is showing the problem?

Thanks!

**Comment by hlabrand** [comment]
[exporter-accents.txt](https://github.com/JasonLautzenheiser/trizbort/files/922400/exporter-accents.txt)

Here it is! (the same goes for the TADS exporter bug)
I had to rename the file into a .txt extension because github didn't want it otherwise, but just change it back to .trizbort.

**Comment by JasonLautzenheiser** [comment]
These issues should be fixed now....I will be putting out a new release most likely today

**Comment by hlabrand** [comment]
Thanks! Just before you do put out a release: a while ago you wrote "Hugo support for exporting Doors...thanks to Andrew Schultz and Hugo Labrande" in Revisions.txt, but it's actually I6 support for exporting doors :)
