### ISSUE TITLE
Room Properties dialog window is not modal

### ISSUE THREAD

**Issue by TextAdventurer** [JasonLautzenheiser/trizbort#332]
I am a professional coder but I am new to GitHub. I would like to contribute to this excellent project in some way - apologies if I have posted this in the wrong place!

The Room Properties dialog window is not modal. It can become lost behind the main window if clicking another taskbar button and then clicking the Trizbort taskbar button. Trizbort appears to have frozen and the user needs to use Alt+Tab to return to the Room Properties window.

**Comment by JasonLautzenheiser** [comment]
Thanks for the report!   If you'd like to submit a pull request with the fix, that would be great as well!

**Comment by JasonLautzenheiser** [comment]
Code has been committed, will be in the next upcoming release
