### ISSUE TITLE
Feature request: Visual Validation of Simple Rules

### ISSUE THREAD

**Issue by ainslec** [JasonLautzenheiser/trizbort#333]
I'm trying to integrate Trizbort into the workflow of a new IF engine, and I have some value-add features I would like to see.

I would like to see some custom map validation settings. How this would work is as follows. Have a validation menu, with some checkboxes in the main window. In this menu have the following options:

* Must Have Unique Names
* Must Have Non Empty Descriptions
* Must Have Non Empty Headers
* Must Have Non Dangling Connections

These validation criteria would be evaluated and if any one of them fails, highlight the room or rooms which fail the validation criteria (might I suggest a big white and red cross drawn over the room in question. Of course, all these validation rules would be switched off by default.

The non-unique names thing is pretty important for importing the .trizbort file into my IF tool. I validate it at my end, but it is a feature that also belongs in the UI. At the moment, if I want to check that everything has a description, I have to double click every box manually. I also have to validate name uniqueness manually.

**Comment by JasonLautzenheiser** [comment]
Those are some decent ideas.  Let me look into this deeper.  Thanks for the suggestions.

**Comment by JasonLautzenheiser** [comment]
@ainslec What do you mean by Headers?  Trizbort won't let you have a room with no name.....so what were your intentions for validating that rooms have headers?

**Comment by JasonLautzenheiser** [comment]
Cool....I thought you might mean the subtitle.

I'm gonna get the validation in and a simple graphical indicator and get a release out, then on a second pass I can look at putting in configurable Regex and perhaps more validations.

BTW:  I'd love to see your tool your building when you have something public....I could also do some linking to your stuff if it's something consumable by the public.   I'm always interesting in seeing how Trizbort is being used.

**Comment by ainslec** [comment]
I'd be happy for you to link to my project once it is public.

**Comment by ainslec** [comment]
Here it is : 

[Introducing Adventuron](https://medium.com/@model_train/introducing-adventuron-4f95909d6aaf)
