### ISSUE TITLE
put "define start/end room" in context menu

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#335]
#334 got me thinking it might be nice to define start/end rooms from the context menu. I think it's the sort of feature request I could knock off with an hour or two, and it'd be fun to write and helpful.

My main question would be, would we want a sub menu with darkness/start/end so the context menu is not too big, and if so, what should it be called?

**Comment by ainslec** [comment]
Room state?

**Comment by andrewschultz** [comment]
That sounds good to me. I'll wait to see if Jason has any opinion.

**Comment by JasonLautzenheiser** [comment]
I'm reviewing this....on the surface Room State seems reasonable...but there seems like given that text, a lot more could go under that (room shape for one)....I'll play with it and see what looks reasonable.

**Comment by JasonLautzenheiser** [comment]
Well, I'm leaning towards Room State....I think the start / end rooms, the darkness and perhaps room shape could go under their....Not sure I want to hide shape under another level of menu though, so I may leave it where it is.
