### ISSUE TITLE
red X in rooms without subtitle

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#345]
Repro:

1. open trizbort with a new file
2. create a room without a subtitle

Is this a feature where I need to turn off an option? It might be neat to have for checking's sake e.g. X out any rooms without description, or X out any rooms without a subject.

**Comment by JasonLautzenheiser** [comment]
This is part of #333 .  There was a bug where the subtitle check was on by default, but I fixed that (perhaps I've not pushed it up yet)....They will all be off by default when released.

Closing this as a non-issue unless I'm missing something.
