### ISSUE TITLE
Should app mention BMPs are 32-bit?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#35]
Saving as a BMP gives a 1000x1000 image at 4 meg. I updated the docs to mention this.

Is it worth saying BMP (32 bit) instead of just BMP in File->Export->Image and Tools->App Settings?

**Comment by JasonLautzenheiser** [comment]
I believe that the standard BMP is always 32bit so probably no need to mention....also I think most people realize that BMPs will most always be larger than PNG / JPEG, so giving too much information may just confuse more than it helps. (My 2 cents anyway)

**Comment by andrewschultz** [comment]
Sounds good. There's information in the documentation.
