### ISSUE TITLE
# of duplicate room names in miscellaneous stats?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#354]
This is something I'd really like to do for whenever the next release is. It's not a huge feature, but I have had a few maps where this would have helped with proofreading, and I suspect the code would not be too tough.

Plus, I want to learn how to use dictionaries/hashing in C#. I've only used them in Perl/Python. I figure I can crib the syntax from CodeExporter.cs's ExportName.

**Comment by JasonLautzenheiser** [comment]
You can also look in the validation code as I'm checking for duplicate names in there as well.

**Comment by andrewschultz** [comment]
Awesome, thanks! Now that I think about it, I suppose a ctrl-shift-f for "Dictionary" would tease everything out.

**Comment by JasonLautzenheiser** [comment]
I refactored the code slightly, but overall this works.
