### ISSUE TITLE
Samples directory

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#37]
I wanted to check on this before creating it.

https://github.com/andrewschultz/trizbort-maps/tree/master/others has 2 files I think are decent candidates for a sample files suite. I don't know if that's enough in quantity to start. I also wonder if we want warnings for slasher swamp, or we'd prefer a more neutral game (it has violence etc.)

I would like to write an HTML file linking to each file with a legend to describe what formatting I used where and why. For instance,

* Slasher swamp: dashed borders = places to search. No borders = to the forest maze
* Luster: Orange = power source that lets you by the train (other orange). No borders/lighter green = loop around. Dashed borders = places where you get a gem.

Also do we want just the .trizbort versions or do we want PNGs/PDF too as well? Maybe even PDF walkthroughs where text is glued on to the maps?

I'm also interested in other game candidates that haven't been done yet. Right now I'm looking at Excelsior, from the 2014 IFComp.

ParserComp had a few good games to map, like Chlorophyll, Adventurer's Garden, and Mean Streets (which David Welbourn already did, but we can show regions and of course refer to his map.)

I'd like to give a good sample of low-middling games to show how frustration can be alleviated quickly, but I'd also like to do some good games like Endless Nameless (I am nearly done with that game and map. I still have to kill the dragon) and Chlorophyll.

**Comment by JasonLautzenheiser** [comment]
I think any number of samples is great and we can of course always expand.   I'm not one to get caught up in warning about "triggers" (unless it's just purely pornographic), so I'm not concerned about that....

**Comment by andrewschultz** [comment]
Awesome--I have a prototype up. I wasn't able to get trizbort files to view in-browser so I just used a PDF. I was thinking it'd be neat to have a game from each IFComp back to 2005 or so, I don't know.
