### ISSUE TITLE
Feature request: Connections to a reference of a room?

### ISSUE THREAD

**Issue by PlNG** [JasonLautzenheiser/trizbort#370]
I think having room references would resolve weird map geometry and the ensuing connection mess made by warps and mazes in which exits reference other rooms in a non-linear fashion (Starting from room 1 go east to room 2, go west to room 3, then east to room 4, then north to room 1, etc.). Clicking these rooms could highlight the referenced room?

Here's what I mean: Scott Adam's Pirate's Cove "maze" segment.

[Messy](https://i.imgur.com/OWBzV7N.png)
[Flattened](https://i.imgur.com/vivBjgJ.png)

Adventureland was much worse.

Also, in making this I discovered that subtitles are not copied with the rooms. Using 1.5.9.9

**Comment by andrewschultz** [comment]
I've run into this too. Games with scrolling/circular maps could definitely use this. Defining a new type seems like no small thing, and it'd probably require a lot of testing, but it could help with a lot of these odd scrolling maps.

**Comment by JasonLautzenheiser** [comment]
I'm not sure this will be too awful to implement on first thought....It will take a bit of testing as Andrew said, but I can see this would be a real useful tool not only for the reasons you state, but for something I've been toying with implementing in a future version as well.

**Comment by JasonLautzenheiser** [comment]
TRIZ-121

**Comment by JasonLautzenheiser** [comment]
@andrewschultz @PlNG This should be in the latest code if you pull it down.  

+ Setting a reference to another room is done through the room properties.
+ The wording on the room will change to indicate a link and a light blue halo will appear around the room.
+ Holding the Ctrl key and clicking on the room will take you to the room in the reference.

If you get a chance, please test this out and see if it meets what you had in mind.  It really wasn't too difficult to implement.
