### ISSUE TITLE
Line in/out text runs into octagonal/elliptical rooms

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#378]
https://gist.github.com/andrewschultz/0a0a694e9af00bf8aa7d2fbef7201587 is the test file I used.

Connectors from an elliptical or octagonal room, if given in/out text, will run into the room body.

I would guess this would be a 3 line fix, e.g. (room shape is octagonal or room shape is elliptical) { if (port is ne/se) x-offset += 10; if (port is nw/sw) x-offset -= 10; }

**Comment by JasonLautzenheiser** [comment]
Not quite as simple as a 3-line fix, but it's fixed now.
