### ISSUE TITLE
"NotARoom" enumeration causes odd room-edit behavior

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#388]
1 new file
2 R to make a room
3 edit the room and click okay

Note that the room's shape changes from square to rounded corners.

This seems to be a result of the GUI interacting with the enumeration. We had assumed that the GUI pull-down to change shapes (Square, Rounded, Octagonal, Ellipse) was the same as the enumeration, but with NotARoom added first, it no longer is.

It looks like a solution is to put NotARoom at the end of the enumeration in Room.cs, instead of the start, but I don't know what this would do for future plans, or how it might destabilize other things.

The new NotARoom also causes some cut/paste exceptions.

**Comment by JasonLautzenheiser** [comment]
Fixed by #396
