### ISSUE TITLE
Tools:Map Settings:About extra whitespace in Description/History text fields

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#391]
This is sort of related to #390. If you have a 6-line description or history, it looks like the line below the 5th is empty. The reality is, it's just a bunch of whitespace a full line can't fit in, but again, I had a half-second panic where I worried my information would be deleted.

I don't know how this would conflict with #390, but it would be neat to 1) tighten the message boxes up a bit and 2) still have a nonintrustive way to be able to indicate they go beyond the message boxes.

**Comment by JasonLautzenheiser** [comment]
Fixed by #397
