### ISSUE TITLE
Add an exporter for Quest

### ISSUE THREAD

**Issue by ThePix** [JasonLautzenheiser/trizbort#392]
Along with Inform 7, Quest is probably one of the top two parser based systems, judging by forum activity, and it would be great if Trizbort supported Quest too.

I have forked the repository, and got a working exporter, so most of the work is done. I ran into problems with details as there seems to be an existing issue with room shapes making it crash. I would like to have the exporter take account of the type of objects in a room. Also regions possibly, but again that seems not to work at the moment.

Is this of interest? Shall I put in a pull request now, and update it later, or wait until the issues are fixed?

**Comment by JasonLautzenheiser** [comment]
Absolutely, I'd love to see an exporter for Quest.  Look forward to a seeing a pull request!

Also if you have more details on the issues you found with room shapes and regions, please create issues for them if you can.  Would love to fix the problem as I wasn't aware of one.

Thanks again!

**Comment by JasonLautzenheiser** [comment]
This has been merged in.  I fixed one small bug in the export to quest that would cause an invalid quest file to be created when two rooms were named the same in Trizbort.

I tried the simple map in Question 5.7 and exports in this case should work fine now.
