### ISSUE TITLE
Setting room shape causes crash

### ISSUE THREAD

**Issue by ThePix** [JasonLautzenheiser/trizbort#394]
This is an issue with the version of Trizbort source as downloaded from Github 22/Jan/18, running through VS2017 on Windows 7.

Create a new room, and double click on it to bring up properties. Click Okay, and the shape changes to rounded corners.

You can change the shapes of rooms via the menu. However, if you go to properties, it will tell you it is actually the next one down the list, and when you click okay, it will become that shape. Going back to properties will show that same shape

Double clicking an octagonal room (set from the menu) throws an exception, line 119, RoomPropertiesDialog.cs, presumabbly because there is no next shape to turn it in to.

Similarly, trying to set the shape to square from the properties throwing an exception at line 1624 of Room.cs, because it is trying to go beyond the start of the list?

It is like the properties dialogue sets one value and the menu sets another, and they are out of step.

Maybe unrelated, but there are no regions listed in the properties dialogue

**Comment by JasonLautzenheiser** [comment]
@ThePix The room issue should be fixed if you get the latest code.   

I've not been able to reproduce the issue with regions.  If you go to map settings and add regions, then go to the properties dialog, they should show up.   Note, there are no regions by default on a new map.  If this is still not working, there must be a strange scenario that I'm not seeing and we can open a new issue with that.

**Comment by ThePix** [comment]
I did not see where to set up regions, so that was my bad!
