### ISSUE TITLE
Adjusting whitespace in pdf/png

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#40]
Currently the whitespace in any pdf/png is 800 pixels = 11.11 inches at 72 DPI.

This seems excessive especially with small maps--a PDF looks shrunk & it's not trivial to cut it down, though CoherentPDF can.

Would it be easier to offer "smart margins" like the following:

each horiz margin = max (100 pixels, 10% of width)
each vert margin = max (100 pixels, 10% of height)

Or let the user choose margin size?

While CoherentPDF is available, the calculation involved makes margin trimming nontrivial.

**Comment by JasonLautzenheiser** [comment]
I want to look at this.

**Comment by andrewschultz** [comment]
Oops. I made a sort-of fix for this before checking the issues. I'm not fully happy with it, as it's not clear whether this should be in the app options or the map options. I put it in the app.

**Comment by JasonLautzenheiser** [comment]
At some point I'd like to redo the options completely, but I think for now the options in app is fine.
