### ISSUE TITLE
Context menu button sometimes disables if used exclusively

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#41]
This is an odd one. When I use the context menu button with a room highlighted, it's sometimes greyed out.

I'm not able to get this reliably if I right-click on a room and then use the context menu. It's only when I use the context-menu key between the right control and right windows.

Test case: 1st version of manor-of-speaking.trizbort
Click on Stumblebum Lane
push context menu key, then escape
ctrl-(numpad 7)
push context menu key, then escape

If you go around the loop at the top, the context menu will eventually disable.

This is easier to produce with a new file than with one you've been tinkering with. So it looks like something's not getting initialized.

https://raw.githubusercontent.com/andrewschultz/trizbort-maps/master/others/manor-of-speaking.trizbort

**Comment by JasonLautzenheiser** [comment]
I believe my menu changes may have fixed this...as I can't reproduce it anymore.
