### ISSUE TITLE
Error on initial saving of map.

### ISSUE THREAD

**Issue by TheDarchy** [JasonLautzenheiser/trizbort#427]
This error has appeared from version 1.6.0 - When saving a map for the first time.

"There was a problem saving the map: The path is not of a legal form."

**Comment by JasonLautzenheiser** [comment]
Was having some computer issues, so wasn't able to to look at this.   Hoping to check it out this weekend.

**Comment by JasonLautzenheiser** [comment]
I can reproduce this in versions 1.6 and 1.6.1, but I can't reproduce it in the current unreleased code.  This should be fixed then in the upcoming release.

I will expedite the release

**Comment by JasonLautzenheiser** [comment]
I should note also, in my testing it appears the file is actually being saved, the error comes after the file is saved despite the misleading error message.

**Comment by TheDarchy** [comment]
That's great news thank you for taking the time to update.
