### ISSUE TITLE
negative values for down/right shift cause 1.7.1 to throw exception

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#451]
1.7.0 is okay.

Test case:

* create new file in 1.7.0
* make a room
* click custom position
* set to -20, -20
* re-open in 1.7.1

There may be a related issue that, in 1.7.1, we cannot define a custom position as negative. It looks like when refactoring the code an unsigned int might've gotten mapped to a signed int.

**Comment by JasonLautzenheiser** [comment]
Thanks @andrewschultz , I will take a look at this.

**Comment by JasonLautzenheiser** [comment]
it currently does not allow of negative numbers, so this should be fixed now.
