### ISSUE TITLE
saving file several times temporarily/harmlessly corrupts "recent maps"

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#454]
1. open a.trizbort in trizbort 1.7.1 (the name is not important. We just want to fill up the recent maps list.)
2. open b.trizbort in trizbort 1.7.1
3. open c.trizbort in trizbort 1.7.1
4. open d.trizbort in trizbort 1.7.1.  Give it a room or two.

Alt-F, R will show d, c, b, a.

5. pick any room, move it one square, and save.
6. repeat 5 several times.

Alt-F, R will show d, c, b, a, d, d, d, d.

7. open any of a/b/c.trizbort.

Note now we are back to 4 files.

It seems we're not trimming the recent maps list correctly after a save, and we need to throw in whatever check we use when we switch files.

**Comment by Nyun0** [comment]
@andrewschultz, can you check out my branch [start-end-copy](https://github.com/Nyun0/trizbort/commits/start-end-copy) if that resolves the issue? [f7dbb9f](https://github.com/Nyun0/trizbort/commit/f7dbb9f58c0dd3d8e5a6768a52bb010877dbc9b0)
