### ISSUE TITLE
Tooltips freeze on move or pan

### ISSUE THREAD

**Issue by Nyun0** [JasonLautzenheiser/trizbort#459]
The room tooltip freeze in place when moving the room or panning the view while the tooltip is displayed.
![tooltip_freeze](https://user-images.githubusercontent.com/44881234/48362792-baee3b00-e6a4-11e8-82a6-1f3d424beb4b.png)

**Comment by JasonLautzenheiser** [comment]
I'm not ready to merge this in....the "fix" adds more flicker and causes the map to not pan smoothly.
