### ISSUE TITLE
Start/End room properties transferred on cut and paste

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#460]
This is a very minor issue, but I stumbled across it.

1. create a map with 2 rooms, start and end
2. highlight all, then copy and paste

After un-highlighting, note we have 2 start rooms and 2 end rooms. This is easy for the user to fix, but it might be nice to remove the "start/end room" flag from any pasted rooms if possible. (It might not be so easy to fix programmatically.)

**Comment by Nyun0** [comment]
Isn't it an easy fix? I guess all it takes is to remove the below two lines in `CopyController.SetRoom`:
`newRoom.IsStartRoom = room.IsStartRoom;`
`newRoom.IsEndRoom = room.IsEndRoom;`

The question is, what should happen if there is cut-paste instead of copy-paste.
