### ISSUE TITLE
Add a hotkey for zoom 100%

### ISSUE THREAD

**Issue by Nyun0** [JasonLautzenheiser/trizbort#464]
First off: need to add the hotkey for setting zoom level for 100%. Zero is my natural candidate for that.

Second: ctrl+ and ctrl- are not working in the same way that ctrl+mouseWheel does.

**Comment by JasonLautzenheiser** [comment]
I believe the Home key does what you're looking for.

**Comment by Nyun0** [comment]
Wow. Didn't notice home actually restores 100% zoom level.

Then all that needs to be done is the ctrl+ and - for consistency with the mouse wheel.

You can assign this issue to me :)

**Comment by JasonLautzenheiser** [comment]
The hotkey for zoom 100% is Home so this is a  non-issue
