### ISSUE TITLE
Spelling Error in Map Statistics (trivial)

### ISSUE THREAD

**Issue by tajmone** [JasonLautzenheiser/trizbort#468]
In Tools -> Map Statistics there is a small spelling error:

    4 custom sconnection

... the 's' of plurality is placed before the word 'connection'.

**Comment by JasonLautzenheiser** [comment]
oopps....thanks for catching that.

**Comment by JasonLautzenheiser** [comment]
fixed with https://github.com/JasonLautzenheiser/trizbort/pull/470
