### ISSUE TITLE
Automapping: can we ignore game title as a room name?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#47]
A part of the Trizbort documentation reads (or used to--I updated it to sound less harsh) "Trizbort's not very bright. It may think the name of the game is a room you're mapping. If so, feel free to delete the room name."

I haven't run across this, but if anyone has more than once, would it be useful/worthwhile to have a "ignore text" function?

**Comment by JasonLautzenheiser** [comment]
It actually does happen to me.  This would be a nice feature to try and implement.

**Comment by JasonLautzenheiser** [comment]
Should be handled a bit better now.  f20be09f354082f4f8e879ebe3436ca6cd9d657b
