### ISSUE TITLE
Inform 7 Export needs quotations around author's name

### ISSUE THREAD

**Issue by no1453** [JasonLautzenheiser/trizbort#479]
I did a quick one-room with Trizbort, with  M. Hoskins set as the author's name in the Map Settings.   After Inform 7 export Inform 7 refused to compile unless I put quotation marks around the name in the Inform editor.   Then everything worked fine.
Speculation: It might have to do with the period in the author's name.

**Comment by JasonLautzenheiser** [comment]
Most likely it is the period.  Thanks for the report.
