### ISSUE TITLE
Octagonal Shaped room created with 1.7.0.0 can not be edited with 1.7.2.0 (exception)

### ISSUE THREAD

**Issue by AnselmD** [JasonLautzenheiser/trizbort#483]
Hi,

I created a map with octagonal shaped rooms, with trizbort 1.7.0.0.
After loading it with 1.7.2.0 i am not able to edit the octagonal shaped rooms:
System.ArgumentOutOfRangeException: Der Wert -15 ist für Value ungültig. Value sollte zwischen 'Minimum' und 'Maximum' liegen.

> Parametername: Value
>    bei System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
>    bei Trizbort.UI.RoomPropertiesDialog.set_ObjectsCustomPositionDown(Int32 value)
>    bei Trizbort.Domain.Elements.Room.showRoomDialog(PropertiesStartType start)
>    bei Trizbort.Domain.Elements.Room.ShowDialog()
> ...

I do not know if this is because the room is octagonal.
The example attached has this error.
[trizbort_test.zip](https://github.com/JasonLautzenheiser/trizbort/files/3389549/trizbort_test.zip)

**Comment by JasonLautzenheiser** [comment]
Thanks for reporting this.  I was able to reproduce it with your sample file and will take a look at it.
