### ISSUE TITLE
pdf output corrupted

### ISSUE THREAD

**Issue by AnselmD** [JasonLautzenheiser/trizbort#484]
In the attached map the pdf output is wrong - rooms are not displayed (Adobe Acrobat Reader).
[testpdf1.zip](https://github.com/JasonLautzenheiser/trizbort/files/3389671/testpdf1.zip)

Screenshot Trizbort
![2019-07-14 11_34_25-testpdf1 - Trizbort - Interactive Fiction Mapper - 1 7 2 0](https://user-images.githubusercontent.com/6770907/61181815-66340300-a62b-11e9-83d8-4e54d404084d.png)

Screenshot PDF:

![2019-07-14 11_32_06-testpdf1 pdf - Adobe Acrobat Reader DC](https://user-images.githubusercontent.com/6770907/61181798-2240fe00-a62b-11e9-83e6-6afb795f67eb.png)

**Comment by JasonLautzenheiser** [comment]
Which PDF reader are you using?  The map is showing up fine for me from the PDF you provided.

**Comment by AnselmD** [comment]
Adobe Acrobat Reader DC 
Continuous 2019.012.20035

**Comment by AnselmD** [comment]
Loading PDF with firefox and chrome is fine.

Enlarging the room, so that the complete text is visible, helps in adobe reader:
HHH  gggggggggg hhhhhhhh JJJJJJJ KKKK LLLLL MMMMM iii.
![2019-07-14 14_36_23-G__testpdf trizbort_ - Trizbort - Interactive Fiction Mapper - 1 7 2 0](https://user-images.githubusercontent.com/6770907/61183719-e74bc400-a644-11e9-848a-d0948824706b.png)

**Comment by JasonLautzenheiser** [comment]
Yes, I'm guessing that the issue may be with acrobat reader.....I've yet to find another pdf viewer that has problems with it.   Gonna close this for now unless.
