### ISSUE TITLE
Required Visual Studio version

### ISSUE THREAD

**Issue by Happy-Ferret** [JasonLautzenheiser/trizbort#486]
Hi there.

I'm trying to build the project from the master branch and am running into a metric ton of build issues (see below).

Does trizbort require specific C# features only available with later releases of Visual Studio?

I'm running Visual Studio 2015 Professional on my development system.

![vs2015](https://user-images.githubusercontent.com/1962554/62539236-08bf5a80-b855-11e9-89b8-3b2351cf1b27.png)

**Comment by JasonLautzenheiser** [comment]
Once I took over the project, I upgraded everything to VS2017 and have recently upgraded to vs2019.... I use the community edition which is a free download.

**Comment by Happy-Ferret** [comment]
Thanks! Tried it at home (I'm not allowed to install the Community Edition at my workplace) and got it to compile instantaneously.
