### ISSUE TITLE
Zooming in too much throws exception

### ISSUE THREAD

**Issue by fredrikr** [JasonLautzenheiser/trizbort#497]
If you zoom in too much on the map, Trizbort throws an Argument out of range excpetion. This can easily happen when using a touchpad to zoom.

I use Trizbort 1.7.0.0 on Windows 10 Pro.

**Comment by JasonLautzenheiser** [comment]
Thanks for reporting this.  I will take a look into it.

**Comment by JasonLautzenheiser** [comment]
This was actually fixed in v1.7.2.   (https://github.com/JasonLautzenheiser/trizbort/issues/447)

https://github.com/JasonLautzenheiser/trizbort/releases/tag/v1.7.2

If you get the latest version, it should be fixed.

**Comment by fredrikr** [comment]
Ah, sorry. I had a look at the trizbort.com the other day to make sure I had the latest version, and the page seems to state that 1.7.0 is the current version. Anyway, I got the new version now, and this issue has been fixed. Thanks!

**Comment by JasonLautzenheiser** [comment]
Hmmm....yes it does.  I need to get that updated.  Thanks again.
