### ISSUE TITLE
1.7.4 gui error

### ISSUE THREAD

**Issue by ximokom** [JasonLautzenheiser/trizbort#556]
![triz174](https://user-images.githubusercontent.com/35869376/160235155-ad2e128d-5569-4c04-b56f-6356ba82e41d.PNG)
windows 7, 1366x768 125% dpi
1.7.2 no problem

**Comment by JasonLautzenheiser** [comment]
very strange..... thanks for the report.  I will take a look at this.

**Comment by ximokom** [comment]
I have checked the latest version and now it works correctly. Thanks :-)
