### ISSUE TITLE
Implement DOORS for the maps.

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#56]

**Comment by JasonLautzenheiser** [comment]
A door could be simply a setting on the connection (or a type of connection).  Trickiest part may be implementing them in the export.....and coming up with some visual way to display the doors on the map so the are distinguishable from normal connections.

**Comment by JasonLautzenheiser** [comment]
Need to have settings for open/closed, openable or not, locked / unlocked, with appropriate visuals.

**Comment by andrewschultz** [comment]
Here's a proposal that may help.

I like the idea of having a default door width, like a stalk length. The door would be a segment perpendicular to the connector at its midpoint (assuming doors are between two rooms), which could be a bit of annoying math, but nothing undoable. If the door is locked, it might be a squiggly line. I don't know if this covers everything, but I hope it's a start.

An open door might intersect the connector fully, while a closed door might have whitespace on each side of the connector.

**Comment by JasonLautzenheiser** [comment]
Initial implementation of doors is now in.  Currently displays icons on the connection if a door.  Only exports to I7
