### ISSUE TITLE
Light Gray Square Lower Right Canvas

### ISSUE THREAD

**Issue by VVindrunner** [JasonLautzenheiser/trizbort#567]
Hello,

This is my first time ever using Github to submit a bug, so apologies if I've gone about this the wrong way.
First off, THANK YOU so much for the continued support of this program. I consider it an essential!

I updated from 1.7.2.0 to the latest (1.7.4.1). In every single map, there is a square in the lower right portion of the canvas. It will cover up any map asset. I'll also try and remember to run the program from another computer and let you know if anything changes.
<img width="722" alt="white background" src="https://user-images.githubusercontent.com/17192128/173247129-ff2c1212-d2b5-47b2-a7d8-414684670abf.png">
<img width="721" alt="grey background" src="https://user-images.githubusercontent.com/17192128/173247135-1e43cd98-08c3-4a49-aede-8f594374ba41.png">

**Comment by JasonLautzenheiser** [comment]
That's really odd, I hadn't noticed that.   I just checked on my machine and sure enough, there it is.   Thanks for reporting that.
