### ISSUE TITLE
Feature: implement alignment of SSE etc. exits

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#63]
The Gemstone Warrior map just sent in the samples might benefit from an "align" tag e.g. the passages south from room 12 are all a bit angly. It would be neat if they could be made straight-vertical.

**Comment by JasonLautzenheiser** [comment]
Probably to do this we'll have to add more ports.   Maybe make the ports more dynamically created based on length of a side.  So have a mininum of 3 per side (and plus the two in each corner)...but that number of ports would grow based on the length with some minimum distance between each.

This might mess with a lot of other things though, so perhaps another idea would be to be able to move ports along a side.  Still keep the same number of ports (5), but allow them to slide so they could be better positioned.
![issue63](https://cloud.githubusercontent.com/assets/1239981/7718012/99e0d782-fe78-11e4-9237-5f90a391b994.png)
