### ISSUE TITLE
name with dashes in runs outside box

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#73]
1) create a new file
2) make a room
3) call it Accardi-by-the-Sea (yeah, I'm mapping Beyond Zork)

An obvious workaround is to make by- the-Sea, but that's a bit awkward. Maybe we can find a way to line-break for dashes as well as spaces?

**Comment by JasonLautzenheiser** [comment]
Good catch....fixed in e986927ea9b573b2d9a24626f0f2a3aff0e9fb4f

**Comment by andrewschultz** [comment]
Verified fixed in the separate binary.
