### ISSUE TITLE
Change link in menu to online docs to point to new documentation

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#74]
http://www.trizbort.com/Docs/index.shtml

**Comment by andrewschultz** [comment]
I'll want to fix the documentation, too...though it's so tough to change gears now.

Also feel free to mention any other documentation things that need updating. I assume I can look at the 1.5.8.10 milestone to figure them out?

**Comment by JasonLautzenheiser** [comment]
No hurry really, I can even update things as I go (I just haven't bothered
yet).  I'm not sure the docs have the stuff for 1.5.8.9 either yet actually.

I'm actually working on another release this week, I'm cleaning up the ZIL
export and may even knock out a few other things also.

Jason

**Comment by andrewschultz** [comment]
Awesome. If you have details you don't want to deal with re the docs, just print them out. Or even just sort of do them halfway and throw them over the wall.
