### ISSUE TITLE
Create an exporter for Hugo

### ISSUE THREAD

**Issue by JasonLautzenheiser** [JasonLautzenheiser/trizbort#79]

**Comment by andrewschultz** [comment]
I've been poking at this and it might be fun, especially since you have bigger things to do.

While Hugo generally uses multiple source files, I think we would have no problem creating one source file that does everything, with a caveat comment of "this is bad programming, but it should compile."

**Comment by JasonLautzenheiser** [comment]
Feel free to try and tackle this.

**Comment by andrewschultz** [comment]
This is fixed mostly but I suspect there's something I've generally missed. Maybe Roody_Yogurt will be able to help. However, Hugo code should export for each room, object and metadata.

**Comment by JasonLautzenheiser** [comment]
I'll close this for now as the importer is in there....as we get feedback we'll open new tasks.
