### ISSUE TITLE
create low granularity bmp export?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#80]
When exporting to png or any bitmap, the graphics try for smoothing room names, etc.

This is nice some of the time but when I want something really compressed, it doesn't work at all.

Is there any way we could allow the user to avoid smoothing when exporting to a bitmap?

**Comment by andrewschultz** [comment]
Apologies in advance for this. This was a shoot first ask questions later sort of bug.

This option is in fact located in the control panel.

http://superuser.com/questions/405066/what-are-all-the-places-where-cleartype-can-be-disabled:

    Global settings
        Open the Control Panel
        type "ClearType" in the search bar
        Open the link
        Uncheck the "Enable Cleartype" checkbox
        Press next-next-next-Finish, ignoring the unexpected and useless configuration options.

It was enough of a nuisance to me I'd like to write it into the documentation. I think a lot of people will want this feature, and it's nontrivial to find. I think people would be happy to know about this.

**Comment by JasonLautzenheiser** [comment]
It might nice to see if i can make it an option that user can set on a map by map basis.  That way they don't have to change their windows settings just to view the map.

Can you attach a sample trizbort file to demonstrate the issue?

**Comment by andrewschultz** [comment]
I wasn't able to attach a trizbort file, but 

https://raw.githubusercontent.com/andrewschultz/trizbort-maps/master/others/beyond_zork.trizbort

shows the disparity. It's 225k with ClearType on but 50k with it off.

As it turns out, there is some color blending with the borders even with cleartype. It would be extra nice if that were avoidable. E.g. if you blow the picture up, the borders go from black to greyish to white. PNG Gauntlet doesn't do much to cut this down. So if there were an option to make things more raster-y, that would be even nicer.

**Comment by JasonLautzenheiser** [comment]
well, i'm not able to really reproduce any issue....Cleartype is turned on and my export images look great.

**Comment by andrewschultz** [comment]
Hm, I stated it kind of wrong...the thing is, I'd like the option -not- to have the blended, more hi-res look, so the letters look "old school." We can do this by tuning clearType off, but it only works for the letters and not for the lines.

This may seem like an odd feature request to make exports less smooth, but it can save a lot of space on PNG exports.

This is a bit minor but I can provide screenshots if you'd like.
