### ISSUE TITLE
1.5.9.1 Rooms:Room Shape menu has inaccurate option names

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#84]
Hand-drawn is actually a different more global option, to determine whether lines all over are wavy or not. So Hand-drawn may be better stated as "rectangular," but ctrl-r is already used.

My recommendation is

Ellipse=ctrl-e
Rounded=ctrl-r
Pointed/Plain=ctrl-p (this accel not in use yet)
Hand-drawn=ctrl-h

Note: after reporting this issue I also noticed that ctrl-h toggles the hand-drawn effect when the room is rectangular. This makes a bit more sense of the whole option, but it also makes the checkbox in tools:map settings:lines and grid for "Hand-drawn" obsolete. We would, to get it in tune with the new features, need to make it a pull-down with all four possibilities...since hand drawn or not is no longer a boolean.

I had assumed that you could have hand-drawn (wavy) ellipses and rounded rectangles, but it seems you can't. So I think we need to make it clear there are 4 options and not a matrix of 2x3 options for line shapes etc. I can of course update the documentation too.

**Comment by andrewschultz** [comment]
Also, on further consideration, now that we have octagons, I think we should make hand-drawn a boolean. It can apply to either octagonal or rectangular shapes. It could be either local to the room or (still) global to the canvas.

If it is local to the room, we may wish to get rid of the global option, since we can just hit ctrl-a and ctrl-h and make things hand-drawn...and we can make a newly created room inherit the last hand-drawn-ness.

**Comment by JasonLautzenheiser** [comment]
Duplicate (sort of) of #294
