### ISSUE TITLE
1.5.9.1: bounding on long name in ellipse

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#86]
The left room in https://www.dropbox.com/s/yfscq912sxfefsq/over-bounds.trizbort?dl=0 has "rastapopoulos" going out of bounds.

To some extent this should be the user's responsibility to make sure this doesn't happen, but I'm wondering if there's a way to at least clip the text that runs over.

**Comment by JasonLautzenheiser** [comment]
0133dd87c58b4170d401957cc822a23225fbacfb
