### ISSUE TITLE
1.5.9.1: should room rounding options persist with a new room?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#87]
Test case:

1. new document
2. push R
3. push ctrl-E
4. push R (or control-arrow)

It would be nice if trizbort used the highlighted room's rounding to create the next one, or if we had the option to do this.

**Comment by JasonLautzenheiser** [comment]
I like this, for the control-arrows....I think R for new room, should stick with the default room shape (currently square)  - #93

**Comment by JasonLautzenheiser** [comment]
0133dd87c58b4170d401957cc822a23225fbacfb
