### ISSUE TITLE
1.5.9.1: octagonal shape for rooms?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#89]
I think it'd be very nice to be like the rooms with rounded edges. It could also designate a "stop" room pretty handily, to indicate a room is a bottleneck. But yeah, this is a definite feature request.

I also think I could add something to the documentation with flowcharts once I write this feature in, because if a map could look like a flowchart, it'd be helpful.

**Comment by JasonLautzenheiser** [comment]
This will make a nice additional shape
