### ISSUE TITLE
Ability to mark part of a script parsed

### ISSUE THREAD

**Issue by matthiaswatkins** [JasonLautzenheiser/trizbort#9]
I tend to play for a bit, automap out an area, then edit the map to add notes, remove unwanted room links that creep in due to teleports, move rooms around, etc. This is great except that if I re-open trizbort with the same script file and try to continue where I left off, it parses the whole script file again, destroying all my edits. I can alleviate this by using separate script files for each session, but it would be nice to be able to have just one. I'm not sure how to allow this, maybe have an in-game trizbort command 'mapped' or something that the automap would scan for the last instance of and only start parsing afterward. I could work on implementation, if you think it would be worthwhile.

**Comment by andrewschultz** [comment]
My vote is, this seems interesting and low-risk. I think @JasonLautzenheiser is working more on the GUI and stylistic aspects so it'd be great to have someone specializing in the automapping.

**Comment by JasonLautzenheiser** [comment]
I like this one also.  Please feel free to work on this and put up a pull request when ready.

**Comment by matthiaswatkins** [comment]
There's an option now (since pull request #17 ) in the automap dialog to continue from the end of the script, which satisfies the spirit of this issue. This can be closed.
