### ISSUE TITLE
1.5.9.1: Elipse ports are a bit too close together

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#91]
If we create an ellipse room, deselect it then hover over it, the NNE/NEE ports appear to be crammed together with the NE ports and a bit far from the N and E ports, respectively.

This is largely aesthetic, and once the ports are connected, they look pretty good. But maybe we could make things equidistant?

**Comment by JasonLautzenheiser** [comment]
I know the ports are an issue.  They were actually the most difficult part ti work even as well as they do.  All these port issues are something i want ti focus on

**Comment by JasonLautzenheiser** [comment]
0133dd87c58b4170d401957cc822a23225fbacfb
