### ISSUE TITLE
Enhancement to stats: connected areas?

### ISSUE THREAD

**Issue by andrewschultz** [JasonLautzenheiser/trizbort#96]
For instance, if we had, say, 4 areas where we pushed R then ctrl-up, right, down and left, Trizbort would recognize this as 4 separate islands.

I don't know if this would be too complex but it might be neat to see. I guess you would loop through all the rooms and see what connects where. Then if one room-loop closed, pick a remaining unused room and see what it loops with. Etc.

Some of this stuff might be better for more advanced stats, and there are much bigger architectural things to do. But this might be a fun exercise.

**Comment by JasonLautzenheiser** [comment]
Not sure of the usefulness of this.
